apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  labels:
    app: flask-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      name: flask-app-pod
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app-container
          image: asilbek5999/python-flask-app:v1 
          ports:
            - containerPort: 5000
